### ISSUE TITLE
Error: Bounds are not valid.

### ISSUE THREAD

**Issue by AbbasAlsbihawi** [a-marcel/nextjs13-app-dynamic-loaded-marker#1]
<img width="983" alt="Screenshot 2023-09-05 at 12 53 07 PM" src="https://github.com/a-marcel/nextjs13-app-dynamic-loaded-marker/assets/43404498/d0c82c6a-0cdc-4783-b4a5-06308f55bca1">

**Comment by a-marcel** [comment]
Hello, thanks for the ticket. It was not visible that i setup this repo to exactly show this issue in react leaflet. I updated the Readme file accordantly. Sorry for the inconvenience.
